spring:
  datasource:
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    p6spy: info
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace



decorator:
  datasource:
    p6spy:
      enable-logging: true
